apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: football-frontend
  template:
    metadata:
      labels:
        app: football-frontend
    spec:
      containers:
        - name: football-frontend
          image: <ACR_NAME>.azurecr.io/football-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: football-frontend
spec:
  type: LoadBalancer
  selector:
    app: football-frontend
  ports:
    - port: 80
      targetPort: 80
